// flow-typed signature: 15cdfdb344fe6fc6a67d997669f01195
// flow-typed version: <<STUB>>/bower-webpack-plugin_v^0.1.9/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bower-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bower-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bower-webpack-plugin/lib/bower-loader' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/lib/bower-plugin-logger' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/lib/bower-plugin-main-resolver' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/lib/bower-plugin-manifest-resolver' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/lib/bower-plugin-utils' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/lib/bower-plugin' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/custom-file' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/custom-module-directories' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/exclusions' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-custom-bower-file/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-custom-file-fallback/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-missing-bower/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-js/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-js/module1' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-mixed-with-subdirs/js/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-mixed/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-provided-a/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-provided-b/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-single-array/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-single-string/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-with-exclusions/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-with-exclusions/module1' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/custom_components/custom-module-multiple-js/module0' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/custom_components/custom-module-multiple-js/module1' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/custom_components/custom-module-single-string/custom-module-single-string-bower' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/custom_components/custom-module-single-string/custom-module-single-string-node' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/custom-module-multiple-js' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/custom-module-single-string' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/integration-with-provide' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-alias' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-custom-bower-file' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-custom-file-fallback' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-missing-bower' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-missing-referenced-file' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-missing' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-multiple-js' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-multiple-mixed-with-subdirs' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-multiple-mixed' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-single-array' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-single-string-css' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-single-string' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/module-with-exclusions' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/fixtures/require-multiple-modules' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/inclusions' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/missing' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/multi-module' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/search-resolve-modules-directories' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/single-module' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/test-utils' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/utils' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/with-module-alias' {
  declare module.exports: any;
}

declare module 'bower-webpack-plugin/test/with-provide-plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bower-webpack-plugin/lib/bower-loader.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/lib/bower-loader'>;
}
declare module 'bower-webpack-plugin/lib/bower-plugin-logger.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/lib/bower-plugin-logger'>;
}
declare module 'bower-webpack-plugin/lib/bower-plugin-main-resolver.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/lib/bower-plugin-main-resolver'>;
}
declare module 'bower-webpack-plugin/lib/bower-plugin-manifest-resolver.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/lib/bower-plugin-manifest-resolver'>;
}
declare module 'bower-webpack-plugin/lib/bower-plugin-utils.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/lib/bower-plugin-utils'>;
}
declare module 'bower-webpack-plugin/lib/bower-plugin.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/lib/bower-plugin'>;
}
declare module 'bower-webpack-plugin/test/custom-file.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/custom-file'>;
}
declare module 'bower-webpack-plugin/test/custom-module-directories.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/custom-module-directories'>;
}
declare module 'bower-webpack-plugin/test/exclusions.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/exclusions'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-custom-bower-file/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-custom-bower-file/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-custom-file-fallback/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-custom-file-fallback/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-missing-bower/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-missing-bower/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-js/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-js/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-js/module1.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-js/module1'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-mixed-with-subdirs/js/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-mixed-with-subdirs/js/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-mixed/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-multiple-mixed/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-provided-a/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-provided-a/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-provided-b/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-provided-b/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-single-array/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-single-array/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-single-string/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-single-string/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-with-exclusions/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-with-exclusions/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/bower_components/module-with-exclusions/module1.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/bower_components/module-with-exclusions/module1'>;
}
declare module 'bower-webpack-plugin/test/fixtures/custom_components/custom-module-multiple-js/module0.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/custom_components/custom-module-multiple-js/module0'>;
}
declare module 'bower-webpack-plugin/test/fixtures/custom_components/custom-module-multiple-js/module1.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/custom_components/custom-module-multiple-js/module1'>;
}
declare module 'bower-webpack-plugin/test/fixtures/custom_components/custom-module-single-string/custom-module-single-string-bower.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/custom_components/custom-module-single-string/custom-module-single-string-bower'>;
}
declare module 'bower-webpack-plugin/test/fixtures/custom_components/custom-module-single-string/custom-module-single-string-node.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/custom_components/custom-module-single-string/custom-module-single-string-node'>;
}
declare module 'bower-webpack-plugin/test/fixtures/custom-module-multiple-js.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/custom-module-multiple-js'>;
}
declare module 'bower-webpack-plugin/test/fixtures/custom-module-single-string.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/custom-module-single-string'>;
}
declare module 'bower-webpack-plugin/test/fixtures/integration-with-provide.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/integration-with-provide'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-alias.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-alias'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-custom-bower-file.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-custom-bower-file'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-custom-file-fallback.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-custom-file-fallback'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-missing-bower.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-missing-bower'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-missing-referenced-file.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-missing-referenced-file'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-missing.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-missing'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-multiple-js.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-multiple-js'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-multiple-mixed-with-subdirs.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-multiple-mixed-with-subdirs'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-multiple-mixed.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-multiple-mixed'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-single-array.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-single-array'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-single-string-css.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-single-string-css'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-single-string.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-single-string'>;
}
declare module 'bower-webpack-plugin/test/fixtures/module-with-exclusions.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/module-with-exclusions'>;
}
declare module 'bower-webpack-plugin/test/fixtures/require-multiple-modules.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/fixtures/require-multiple-modules'>;
}
declare module 'bower-webpack-plugin/test/inclusions.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/inclusions'>;
}
declare module 'bower-webpack-plugin/test/missing.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/missing'>;
}
declare module 'bower-webpack-plugin/test/multi-module.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/multi-module'>;
}
declare module 'bower-webpack-plugin/test/search-resolve-modules-directories.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/search-resolve-modules-directories'>;
}
declare module 'bower-webpack-plugin/test/single-module.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/single-module'>;
}
declare module 'bower-webpack-plugin/test/test-utils.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/test-utils'>;
}
declare module 'bower-webpack-plugin/test/utils.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/utils'>;
}
declare module 'bower-webpack-plugin/test/with-module-alias.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/with-module-alias'>;
}
declare module 'bower-webpack-plugin/test/with-provide-plugin.js' {
  declare module.exports: $Exports<'bower-webpack-plugin/test/with-provide-plugin'>;
}
