// flow-typed signature: a664fbe10da76696bff6a2ca28c74309
// flow-typed version: <<STUB>>/mockjs_v^1.0.1-beta3/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mockjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mockjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mockjs/dist/mock-min' {
  declare module.exports: any;
}

declare module 'mockjs/dist/mock' {
  declare module.exports: any;
}

declare module 'mockjs/gulpfile' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/constant' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/handler' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/parser' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/address_dict' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/address' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/basic' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/color_convert' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/color_dict' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/color' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/date' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/helper' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/image' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/misc' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/name' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/text' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/random/web' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/regexp/handler' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/regexp' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/regexp/parser' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/schema' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/schema/schema' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/util' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/valid' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/valid/valid' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/xhr' {
  declare module.exports: any;
}

declare module 'mockjs/src/mock/xhr/xhr' {
  declare module.exports: any;
}

declare module 'mockjs/test/materiels/noop' {
  declare module.exports: any;
}

declare module 'mockjs/test/test.coveralls' {
  declare module.exports: any;
}

declare module 'mockjs/test/test.mock.mock' {
  declare module.exports: any;
}

declare module 'mockjs/test/test.mock.random' {
  declare module.exports: any;
}

declare module 'mockjs/test/test.mock.request' {
  declare module.exports: any;
}

declare module 'mockjs/test/test.mock.schema' {
  declare module.exports: any;
}

declare module 'mockjs/test/test.mock.spec.dpd' {
  declare module.exports: any;
}

declare module 'mockjs/test/test.mock.spec.dtd' {
  declare module.exports: any;
}

declare module 'mockjs/test/test.mock.valid' {
  declare module.exports: any;
}

declare module 'mockjs/test/valid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mockjs/dist/mock-min.js' {
  declare module.exports: $Exports<'mockjs/dist/mock-min'>;
}
declare module 'mockjs/dist/mock.js' {
  declare module.exports: $Exports<'mockjs/dist/mock'>;
}
declare module 'mockjs/gulpfile.js' {
  declare module.exports: $Exports<'mockjs/gulpfile'>;
}
declare module 'mockjs/src/mock.js' {
  declare module.exports: $Exports<'mockjs/src/mock'>;
}
declare module 'mockjs/src/mock/constant.js' {
  declare module.exports: $Exports<'mockjs/src/mock/constant'>;
}
declare module 'mockjs/src/mock/handler.js' {
  declare module.exports: $Exports<'mockjs/src/mock/handler'>;
}
declare module 'mockjs/src/mock/parser.js' {
  declare module.exports: $Exports<'mockjs/src/mock/parser'>;
}
declare module 'mockjs/src/mock/random/address_dict.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/address_dict'>;
}
declare module 'mockjs/src/mock/random/address.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/address'>;
}
declare module 'mockjs/src/mock/random/basic.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/basic'>;
}
declare module 'mockjs/src/mock/random/color_convert.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/color_convert'>;
}
declare module 'mockjs/src/mock/random/color_dict.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/color_dict'>;
}
declare module 'mockjs/src/mock/random/color.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/color'>;
}
declare module 'mockjs/src/mock/random/date.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/date'>;
}
declare module 'mockjs/src/mock/random/helper.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/helper'>;
}
declare module 'mockjs/src/mock/random/image.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/image'>;
}
declare module 'mockjs/src/mock/random/index' {
  declare module.exports: $Exports<'mockjs/src/mock/random'>;
}
declare module 'mockjs/src/mock/random/index.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random'>;
}
declare module 'mockjs/src/mock/random/misc.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/misc'>;
}
declare module 'mockjs/src/mock/random/name.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/name'>;
}
declare module 'mockjs/src/mock/random/text.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/text'>;
}
declare module 'mockjs/src/mock/random/web.js' {
  declare module.exports: $Exports<'mockjs/src/mock/random/web'>;
}
declare module 'mockjs/src/mock/regexp/handler.js' {
  declare module.exports: $Exports<'mockjs/src/mock/regexp/handler'>;
}
declare module 'mockjs/src/mock/regexp/index' {
  declare module.exports: $Exports<'mockjs/src/mock/regexp'>;
}
declare module 'mockjs/src/mock/regexp/index.js' {
  declare module.exports: $Exports<'mockjs/src/mock/regexp'>;
}
declare module 'mockjs/src/mock/regexp/parser.js' {
  declare module.exports: $Exports<'mockjs/src/mock/regexp/parser'>;
}
declare module 'mockjs/src/mock/schema/index' {
  declare module.exports: $Exports<'mockjs/src/mock/schema'>;
}
declare module 'mockjs/src/mock/schema/index.js' {
  declare module.exports: $Exports<'mockjs/src/mock/schema'>;
}
declare module 'mockjs/src/mock/schema/schema.js' {
  declare module.exports: $Exports<'mockjs/src/mock/schema/schema'>;
}
declare module 'mockjs/src/mock/util.js' {
  declare module.exports: $Exports<'mockjs/src/mock/util'>;
}
declare module 'mockjs/src/mock/valid/index' {
  declare module.exports: $Exports<'mockjs/src/mock/valid'>;
}
declare module 'mockjs/src/mock/valid/index.js' {
  declare module.exports: $Exports<'mockjs/src/mock/valid'>;
}
declare module 'mockjs/src/mock/valid/valid.js' {
  declare module.exports: $Exports<'mockjs/src/mock/valid/valid'>;
}
declare module 'mockjs/src/mock/xhr/index' {
  declare module.exports: $Exports<'mockjs/src/mock/xhr'>;
}
declare module 'mockjs/src/mock/xhr/index.js' {
  declare module.exports: $Exports<'mockjs/src/mock/xhr'>;
}
declare module 'mockjs/src/mock/xhr/xhr.js' {
  declare module.exports: $Exports<'mockjs/src/mock/xhr/xhr'>;
}
declare module 'mockjs/test/materiels/noop.js' {
  declare module.exports: $Exports<'mockjs/test/materiels/noop'>;
}
declare module 'mockjs/test/test.coveralls.js' {
  declare module.exports: $Exports<'mockjs/test/test.coveralls'>;
}
declare module 'mockjs/test/test.mock.mock.js' {
  declare module.exports: $Exports<'mockjs/test/test.mock.mock'>;
}
declare module 'mockjs/test/test.mock.random.js' {
  declare module.exports: $Exports<'mockjs/test/test.mock.random'>;
}
declare module 'mockjs/test/test.mock.request.js' {
  declare module.exports: $Exports<'mockjs/test/test.mock.request'>;
}
declare module 'mockjs/test/test.mock.schema.js' {
  declare module.exports: $Exports<'mockjs/test/test.mock.schema'>;
}
declare module 'mockjs/test/test.mock.spec.dpd.js' {
  declare module.exports: $Exports<'mockjs/test/test.mock.spec.dpd'>;
}
declare module 'mockjs/test/test.mock.spec.dtd.js' {
  declare module.exports: $Exports<'mockjs/test/test.mock.spec.dtd'>;
}
declare module 'mockjs/test/test.mock.valid.js' {
  declare module.exports: $Exports<'mockjs/test/test.mock.valid'>;
}
declare module 'mockjs/test/valid.js' {
  declare module.exports: $Exports<'mockjs/test/valid'>;
}
